### PR TITLE
Add missing classes to typings

### PR DESCRIPTION
**Pull request by The-Cat-In-The-Hat**

### CODE REVIEW

**Comment by The-Cat-In-The-Hat** [comment]
I added some type aliases. Is it ok now?

**Comment by brandonlehmann** [comment]
> I added some type aliases. Is it ok now?

Let me, um, phone a friend since typescript isn't my thing.

@zpalmtree do you mind making sure this doesn't break anything up your way?

**Comment by zpalmtree** [comment]
> > I added some type aliases. Is it ok now?
> 
> Let me, um, phone a friend since typescript isn't my thing.
> 
> @zpalmtree do you mind making sure this doesn't break anything up your way?

I get a couple of type errors.

1) `Output` expects a `transactionKey` and `publicEphemeral` property, however those properties are not used in `createTransaction`, so I'm getting a type error from them being missing. Perhaps they should be updated in both docs to be an optional property?

2) `transactionKeys` is present on the `transaction` object returned from `createTransaction`, but this is not present in the jsdoc nor typescript

3) `amount` is now potentially undefined, which is causing an error, but this is a failure of the previous documentation imo, so doesn't need rectifying.

4) `createTransaction` is documented in the jsdoc and typescript as returning `boolean | CreatedTransaction`, but I'm not seeing a codepath which returns that.

I see @The-Cat-In-The-Hat has fixed these type errors on the pull request he made to the backend, but obviously there may be other typescript users out there.

**Comment by brandonlehmann** [comment]
> > > I added some type aliases. Is it ok now?
> > 
> > 
> > Let me, um, phone a friend since typescript isn't my thing.
> > @zpalmtree do you mind making sure this doesn't break anything up your way?
> 
> I get a couple of type errors.
> 
> 1. `Output` expects a `transactionKey` and `publicEphemeral` property, however those properties are not used in `createTransaction`, so I'm getting a type error from them being missing. Perhaps they should be updated in both docs to be an optional property?

Which `Output`?

> 2. `transactionKeys` is present on the `transaction` object returned from `createTransaction`, but this is not present in the jsdoc nor typescript

Added to jsdoc

> 3. `amount` is now potentially undefined, which is causing an error, but this is a failure of the previous documentation imo, so doesn't need rectifying.

Please link?

> 4. `createTransaction` is documented in the jsdoc and typescript as returning `boolean | CreatedTransaction`, but I'm not seeing a codepath which returns a boolean.

Corrected in jsdoc

> 
> I see @The-Cat-In-The-Hat has fixed these type errors on the pull request he made to the backend, but obviously there may be other typescript users out there.

**Comment by zpalmtree** [comment]
>Which Output?

Apologies, I see now it's [`GeneratedInput`](https://utils.turtlecoin.dev/CryptoNote.html#.GeneratedInput) on the `input` of [`Output`](https://utils.turtlecoin.dev/CryptoNote.html#.Output).

>Please link?

I use the `amount` returned by the [`GeneratedTransaction`](https://utils.turtlecoin.dev/CryptoNote.html#.GeneratedTransaction) , then the [`Transaction`](https://utils.turtlecoin.dev/Transaction.html) object on that, then the [`inputs`](https://utils.turtlecoin.dev/Transaction.html#.TransactionInput) array on that, which has an optional `amount` property since it's only present on `02` inputs.

**Comment by The-Cat-In-The-Hat** [comment]
Sorry for delayed response. I see the `transactionKeys` property is now present on the `Transaction` class, but not on the `GeneratedTransaction` which is what `createTransaction` returns. I believe I have updated all the issues flagged up.

**Comment by brandonlehmann** [comment]
Fully typed everything coming in https://github.com/turtlecoin/turtlecoin-utils/tree/v2.x.x

**Pull request closed without merging**
